/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.PACIENTES DROP CONSTRAINT PACIENTES_PK;
ALTER TABLE LABDATABASE.MEDICOS DROP CONSTRAINT MEDICOS_PK;
ALTER TABLE LABDATABASE.ESPECIALIDADES DROP CONSTRAINT ESPECIALIDADES_PK;
ALTER TABLE LABDATABASE.PRODUTOS DROP CONSTRAINT PRODUTOS_PK;
ALTER TABLE LABDATABASE.ITENS_PEDIDO DROP CONSTRAINT ITENS_PEDIDO_PK;

/*Apaga as tabelas*/  --- #
DROP TABLE LABDATABASE.MEDICOS;
DROP TABLE LABDATABASE.PACIENTES;
DROP TABLE LABDATABASE.CONSULTAS;
DROP TABLE LABDATABASE.ESPECIALIDADES;
DROP TABLE LABDATABASE.ESPECIALIDADES;

/*Apaga as sequences*/
-- DROP SEQUENCE LABDATABASE.PEDIDOS_CODIGO_PEDIDO_SEQ;
-- DROP SEQUENCE LABDATABASE.ITENS_PEDIDO_CODIGO_ITEM_SEQ;
-- DROP SEQUENCE LABDATABASE.PRODUTOS_CODIGO_PRODUTO_SEQ;

/*Cria as tabelas*/  --- #
CREATE TABLE LABDATABASE.PACIENTES (
    ID_PACIENTE NUMERIC NOT NULL, 
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(13) NOT NULL,
    SEXO VARCHAR(1) NOT NULL, 
    EMAIL VARCHAR(100) NOT NULL, 
    CEP VARCHAR(9) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(13) NOT NULL,
    CONSTRAINT PACIENTES_PK PRIMARY KEY (ID_PACIENTE)
);

CREATE TABLE LABDATABASE.MEDICOS (
    ID_MEDICO NUMERIC NOT NULL, 
    NOME VARCHAR(100) NOT NULL,
    CRM VARCHAR(9) NOT NULL,
    TELEFONE VARCHAR(13) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CEP VARCHAR(9) NOT NULL, 
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CONTRATACAO DATE NOT NULL, 
    DATA_REGISTRO DATE NOT NULL,
    ID_ESPECIALIDADE NUMERIC NOT NULL,
    CONSTRAINT MEDICOS_PK PRIMARY KEY (ID_MEDICO)
);

CREATE TABLE LABDATABASE.ESPECIALIDADES (
    ID_ESPECIALIDADE NUMERIC NOT NULL,
    NOME_ESPECIALIDADE VARCHAR(100) NOT NULL,
    CONSTRAINT ESPECIALIDADES_PK PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE LABDATABASE.PRODUTOS (
                CODIGO_PRODUTO NUMBER NOT NULL,
                DESCRICAO_PRODUTO VARCHAR2(255) NOT NULL,
                CONSTRAINT PRODUTOS_PK PRIMARY KEY (CODIGO_PRODUTO)
);

CREATE TABLE LABDATABASE.ITENS_PEDIDO (
                CODIGO_ITEM_PEDIDO NUMBER NOT NULL,
                QUANTIDADE NUMBER(9,3) NOT NULL,
                VALOR_UNITARIO NUMBER(9,2) NOT NULL,
                CODIGO_PEDIDO NUMBER NOT NULL,
                CODIGO_PRODUTO NUMBER NOT NULL,
                CONSTRAINT ITENS_PEDIDO_PK PRIMARY KEY (CODIGO_ITEM_PEDIDO)
);

/*Cria as sequences*/
-- CREATE SEQUENCE LABDATABASE.PEDIDOS_CODIGO_PEDIDO_SEQ;
-- CREATE SEQUENCE LABDATABASE.PRODUTOS_CODIGO_PRODUTO_SEQ;
-- CREATE SEQUENCE LABDATABASE.ITENS_PEDIDO_CODIGO_ITEM_SEQ;

-- /*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.MEDICOS ADD CONSTRAINT MEDICOS_ESPECIALIDADE_FK
FOREIGN KEY (ID_ESPECIALIDADE)
REFERENCES LABDATABASE.ESPECIALIDADE (ID_ESPECIALIDADE)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.PEDIDOS ADD CONSTRAINT CLIENTES_PEDIDOS_FK
FOREIGN KEY (CPF)
REFERENCES LABDATABASE.CLIENTES (CPF)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.ITENS_PEDIDO ADD CONSTRAINT PEDIDOS_ITENS_PEDIDO_FK
FOREIGN KEY (CODIGO_PEDIDO)
REFERENCES LABDATABASE.PEDIDOS (CODIGO_PEDIDO)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.ITENS_PEDIDO ADD CONSTRAINT PRODUTOS_ITENS_PEDIDO_FK
FOREIGN KEY (CODIGO_PRODUTO)
REFERENCES LABDATABASE.PRODUTOS (CODIGO_PRODUTO)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.PACIENTES TO LABDATABASE;
GRANT ALL ON LABDATABASE.MEDICOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.CONSULTAS TO LABDATABASE;
GRANT ALL ON LABDATABASE.ESPECIALIDADES TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;